Comercio/FrontEnd/Models/ErrorViewModel.cs
namespace FrontEnd.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Comercio/FrontEnd/Models/ProveedorViewModel.cs
namespace FrontEnd.Models
{
    public class ProveedorViewModel
    {
        public int CodProveedor { get; set; }
        public string NombreProveedor { get; set; } = null!;
        public string? Telefono { get; set; }
        public string? Direccion { get; set; }
        public string? CodigoArchivo { get; set; }
    }
}

Comercio/FrontEnd/Controllers/HomeController.cs
using FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Comercio/FrontEnd/Controllers/ProveedorController.cs
using FrontEnd.Helpers;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class ProveedorController : Controller
    {
        ProveedorHelper proveedorHelper;

        // GET: ProveedorController
        public ActionResult Index()
        {
            proveedorHelper = new ProveedorHelper();
            List<ProveedorViewModel> list = proveedorHelper.GetAll();

            return View(list);
        }

        // GET: ProveedorController/Details/5
        public ActionResult Details(int id)
        {
            proveedorHelper = new ProveedorHelper();
            ProveedorViewModel proveedor = proveedorHelper.GetById(id);

            return View(proveedor);
        }

        // GET: ProveedorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProveedorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProveedorViewModel proveedor)
        {
            try
            {
                proveedorHelper = new ProveedorHelper();
                proveedor = proveedorHelper.Add(proveedor);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController/Edit/5
        public ActionResult Edit(int id)
        {
            proveedorHelper = new ProveedorHelper();
            ProveedorViewModel proveedor = proveedorHelper.GetById(id);

            return View(proveedor);
        }

        // POST: ProveedorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProveedorViewModel proveedor)
        {
            try
            {
                proveedorHelper = new ProveedorHelper();
                proveedor = proveedorHelper.Edit(proveedor);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProveedorController/Delete/5
        public ActionResult Delete(int id)
        {
            proveedorHelper = new ProveedorHelper();
            ProveedorViewModel proveedor= proveedorHelper.GetById(id);
            return View(proveedor);
        }

        // POST: ProveedorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ProveedorViewModel proveedor)
        {
            try
            {
                proveedorHelper = new ProveedorHelper();
                proveedorHelper.Delete(proveedor.CodProveedor);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Comercio/FrontEnd/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Aprende <a href="https://docs.microsoft.com/aspnet/core">como crear Web apps con ASP.NET Core</a>.</p>
</div>

Comercio/FrontEnd/Views/Proveedor/Create.cshtml
@model FrontEnd.Models.ProveedorViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Crear</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         
            <div class="form-group">
                <label asp-for="NombreProveedor" class="control-label"></label>
                <input asp-for="NombreProveedor" class="form-control" />
                <span asp-validation-for="NombreProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoArchivo" class="control-label"></label>
                <input asp-for="CodigoArchivo" class="form-control" />
                <span asp-validation-for="CodigoArchivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comercio/FrontEnd/Views/Proveedor/Delete.cshtml
@model FrontEnd.Models.ProveedorViewModel

@{
    ViewData["Title"] = "Delete";
}



<h3>Seguro que quieres borrar este registro?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoArchivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoArchivo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        @Html.HiddenFor(Model=>Model.CodProveedor)
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver a la lista</a>
    </form>
</div>

Comercio/FrontEnd/Views/Proveedor/Details.cshtml
@model FrontEnd.Models.ProveedorViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreProveedor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreProveedor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoArchivo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoArchivo)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new {  id = Model.CodProveedor  }) |
    <a asp-action="Index">Volver a la lista</a>
</div>

Comercio/FrontEnd/Views/Proveedor/Edit.cshtml
@model FrontEnd.Models.ProveedorViewModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Editar</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @Html.HiddenFor(Model=>Model.CodProveedor)

            <div class="form-group">
                <label asp-for="NombreProveedor" class="control-label"></label>
                <input asp-for="NombreProveedor" class="form-control" />
                <span asp-validation-for="NombreProveedor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoArchivo" class="control-label"></label>
                <input asp-for="CodigoArchivo" class="form-control" />
                <span asp-validation-for="CodigoArchivo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Comercio/FrontEnd/Views/Proveedor/Index.cshtml
@model IEnumerable<FrontEnd.Models.ProveedorViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Inicio</h1>

<p>
    <a asp-action="Create">Crear un nuevo proveedor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodProveedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreProveedor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodigoArchivo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CodProveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreProveedor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodigoArchivo)
            </td>
            <td>
                    @Html.ActionLink("Editar", "Edit", new { id=item.CodProveedor  }) |
                    @Html.ActionLink("Detalles", "Details", new { id=item.CodProveedor }) |
                    @Html.ActionLink("Eliminar", "Delete", new { id=item.CodProveedor })
            </td>
        </tr>
}
    </tbody>
</table>

Comercio/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Proveedor" asp-action="Index">Proveedores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>